### ISSUE TITLE
Populate side navigation bar

### ISSUE THREAD

**Issue by JuCJeff** [nicholasspiroff/iNav-UW#16]
**Summary**
The sidebar of the application could be populated.

**Description**
A sidebar is provided in the application, but no buttons are present in there. 

**Severity**
Enhancement

**Suggestion**
Could add a log out button or a profile button in the side navigation bar. Buttons like Bathrooms, Bubblers, Elevators, Exits or even frequently visited rooms could all be added to the side bar.

**Comment by nicholasspiroff** [comment]
Added logout and about buttons to the side menu.
