### ISSUE TITLE
No indication given when sign up

### ISSUE THREAD

**Issue by JuCJeff** [nicholasspiroff/iNav-UW#3]
**Summary**
There was no indication on whether a new user successfully signed up for an account or not.

**Description**
When the user clicked on the sign-up button, it waited a couple seconds not giving any indication of whether an error occurs or the app is loading.

**Severity**
Trivial

**Suggestion**
Could use a toast or some form of indication to let the user know if the application is still loading or there are some forms of issues occurring that stopped them from signing up(E-mail already existed, wrong format e-mail, connection error etc.)

**Comment by JuCJeff** [comment]
It eventually let us sign up, but delayed a couple seconds. An indication of the application loading will still be very useful.

**Comment by nicholasspiroff** [comment]
Added an activity indicator and label that show the user signup is in progress.
