### ISSUE TITLE
Instruction on setting up application on phone devices

### ISSUE THREAD

**Issue by JuCJeff** [nicholasspiroff/iNav-UW#5]
**Summary**
There is no documentation for how to set up the application on phone devices.

**Description**
No clear documentation was given for setting up the test environment on an iPhone which could be confusing.

**Severity**
Critical

**Suggestion**
Add prompt documentation for the tester to set up Xcode application on their phone with ease.

**Comment by nicholasspiroff** [comment]
There is very clear documentation in the README.md in the "Testing" branch you were linked to.
