### ISSUE TITLE
Password lengths issue

### ISSUE THREAD

**Issue by JuCJeff** [nicholasspiroff/iNav-UW#7]
**Summary**
When a user tries to login or to sign up, the password lengths can cause problems.

**Description**
When a user wants to sign up or log in to an account, a password less than 8 characters will not be accepted. Yet the app didn't give any indication of that being the case, and the user will just be left hanging.

**Severity**
Blocker

**Suggestion**
Add a toast or certain forms of implication to inform the user that the password needs to be 8 characters or longer.

**Comment by nicholasspiroff** [comment]
Added more password requirements with error messages that notify the user if their password is not up to par.
